### ISSUE TITLE
package relative imports

### ISSUE THREAD

**Issue by Veryyes** [anacostiaAI/anacostia-pipeline#8]
Update all imports to use **package relative imports**

e.g.
```python
from .base import BaseNode
```

- [x] Remove weird conditional imports

This is a python package with python modules inside, not python scripts; If a file isn't suppose to be invoked as a script to be run, then there should **not** be any imports of internal modules that look like:
```python
if __name__ == "__main__":
    from base import BaseNode
else:
    from engine.base import BaseNode
```

- [x] No modification to `sys.path` to import modules from within the package

This is just gross bad practice. Just import it correctly.
```python
import sys
sys.path.append(os.path.abspath('..'))
sys.path.append(os.path.abspath('../anacostia_pipeline'))
```

**Comment by mdo6180** [comment]
all sys.path is removed and replaced with relative imports.
